version: "3.9"
services:
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    networks:
      - sandbox

  postgresql:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - sandbox

networks:
  sandbox:
    name: "sandbox-network"